In [27]:
import pandas as pd

In [28]:
pd.__version__

'2.2.3'

In [29]:
df = pd.read_csv("credit_customers.csv")

In [30]:
df.head(10)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
5,no checking,36.0,existing paid,education,9055.0,no known savings,1<=X<4,2.0,male single,none,...,no known property,35.0,none,for free,1.0,unskilled resident,2.0,yes,yes,good
6,no checking,24.0,existing paid,furniture/equipment,2835.0,500<=X<1000,>=7,3.0,male single,none,...,life insurance,53.0,none,own,1.0,skilled,1.0,none,yes,good
7,0<=X<200,36.0,existing paid,used car,6948.0,<100,1<=X<4,2.0,male single,none,...,car,35.0,none,rent,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
8,no checking,12.0,existing paid,radio/tv,3059.0,>=1000,4<=X<7,2.0,male div/sep,none,...,real estate,61.0,none,own,1.0,unskilled resident,1.0,none,yes,good
9,0<=X<200,30.0,critical/other existing credit,new car,5234.0,<100,unemployed,4.0,male mar/wid,none,...,car,28.0,none,own,2.0,high qualif/self emp/mgmt,1.0,none,yes,bad

In [31]:
df.isnull().sum()

checking_status           0
duration                  0
credit_history            0
purpose                   0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         1000 non-null   object
 1   duration                1000 non-null   float64
 2   credit_history          1000 non-null   object
 3   purpose                 1000 non-null   object
 4   credit_amount           1000 non-null   float64
 5   savings_status          1000 non-null   object
 6   employment              1000 non-null   object
 7   installment_commitment  1000 non-null   float64
 8   personal_status         1000 non-null   object
 9   other_parties           1000 non-null   object
 10  residence_since         1000 non-null   float64
 11  property_magnitude      1000 non-null   object
 12  age                     1000 non-null   float64
 13  other_payment_plans     1000 non-null   object
 14  housing                 1000 non-null   object
 15  existing_credits        1000 non-null   float64
 16  job                     1000 non-null   object
 17  num_dependents          1000 non-null   float64
 18  own_telephone           1000 non-null   object
 19  foreign_worker          1000 non-null   object
 20  class                   1000 non-null   object
dtypes: float64(7), object(14)
memory usage: 164.2+ KB

In [33]:
df.shape

(1000, 21)

In [34]:
df.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [35]:
df.columns

Index(['checking_status', 'duration', 'credit_history', 'purpose',
       'credit_amount', 'savings_status', 'employment',
       'installment_commitment', 'personal_status', 'other_parties',
       'residence_since', 'property_magnitude', 'age', 'other_payment_plans',
       'housing', 'existing_credits', 'job', 'num_dependents', 'own_telephone',
       'foreign_worker', 'class'],
      dtype='object')

In [36]:
df.drop(columns = ['checking_status', 'duration', 'credit_history' , 'purpose', 'other_parties', 'residence_since', 'property_magnitude', 'other_payment_plans', 'savings_status', 'num_dependents', 'housing', 'foreign_worker'], inplace=True, errors='ignore')

In [37]:
df.columns

Index(['credit_amount', 'employment', 'installment_commitment',
       'personal_status', 'age', 'existing_credits', 'job', 'own_telephone',
       'class'],
      dtype='object')

In [40]:
df_new_columns = []
for i in df.columns:
    df_new_columns.append(i.capitalize())

In [41]:
df.columns = df_new_columns

In [42]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2.0,skilled,yes,good
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1.0,skilled,none,bad
2,2096.0,4<=X<7,2.0,male single,49.0,1.0,unskilled resident,none,good
3,7882.0,4<=X<7,2.0,male single,45.0,1.0,skilled,none,good
4,4870.0,1<=X<4,3.0,male single,53.0,2.0,skilled,none,bad
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1.0,unskilled resident,none,good
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1.0,high qualif/self emp/mgmt,yes,good
997,804.0,>=7,4.0,male single,38.0,1.0,skilled,none,good
998,1845.0,1<=X<4,4.0,male single,23.0,1.0,skilled,yes,bad
999,4576.0,unemployed,3.0,male single,27.0,1.0,skilled,none,good

In [43]:
# for data cleaning, first we drop reduntant columns meaning which will not give us any benefit

In [44]:
#then we just capitalize it and now we drop duplicates and naN values if we find any

In [45]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [46]:
df.duplicated().sum()

np.int64(0)

In [47]:
df.drop_duplicates(inplace=True) #for dropping duplicate values

In [48]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2.0,skilled,yes,good
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1.0,skilled,none,bad
2,2096.0,4<=X<7,2.0,male single,49.0,1.0,unskilled resident,none,good
3,7882.0,4<=X<7,2.0,male single,45.0,1.0,skilled,none,good
4,4870.0,1<=X<4,3.0,male single,53.0,2.0,skilled,none,bad
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1.0,unskilled resident,none,good
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1.0,high qualif/self emp/mgmt,yes,good
997,804.0,>=7,4.0,male single,38.0,1.0,skilled,none,good
998,1845.0,1<=X<4,4.0,male single,23.0,1.0,skilled,yes,bad
999,4576.0,unemployed,3.0,male single,27.0,1.0,skilled,none,good

In [49]:
df.isna().sum()

Credit_amount             0
Employment                0
Installment_commitment    0
Personal_status           0
Age                       0
Existing_credits          0
Job                       0
Own_telephone             0
Class                     0
dtype: int64

In [50]:
df.dropna(inplace=True) #to drop naN values

In [51]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2.0,skilled,yes,good
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1.0,skilled,none,bad
2,2096.0,4<=X<7,2.0,male single,49.0,1.0,unskilled resident,none,good
3,7882.0,4<=X<7,2.0,male single,45.0,1.0,skilled,none,good
4,4870.0,1<=X<4,3.0,male single,53.0,2.0,skilled,none,bad
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1.0,unskilled resident,none,good
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1.0,high qualif/self emp/mgmt,yes,good
997,804.0,>=7,4.0,male single,38.0,1.0,skilled,none,good
998,1845.0,1<=X<4,4.0,male single,23.0,1.0,skilled,yes,bad
999,4576.0,unemployed,3.0,male single,27.0,1.0,skilled,none,good

In [56]:
df['Class'] = df['Class'].apply(lambda x:1 if x == 'good' else 0)

In [57]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2.0,skilled,yes,1
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1.0,skilled,none,0
2,2096.0,4<=X<7,2.0,male single,49.0,1.0,unskilled resident,none,1
3,7882.0,4<=X<7,2.0,male single,45.0,1.0,skilled,none,1
4,4870.0,1<=X<4,3.0,male single,53.0,2.0,skilled,none,0
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1.0,unskilled resident,none,1
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1.0,high qualif/self emp/mgmt,yes,1
997,804.0,>=7,4.0,male single,38.0,1.0,skilled,none,1
998,1845.0,1<=X<4,4.0,male single,23.0,1.0,skilled,yes,0
999,4576.0,unemployed,3.0,male single,27.0,1.0,skilled,none,1

In [58]:
df['Own_telephone'].nunique()

2

In [59]:
df['Own_telephone'].unique()

array(['yes', 'none'], dtype=object)

In [61]:
df['Own_telephone'] = df['Own_telephone'].apply(lambda x:1 if x == 'yes' else 0)

In [62]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2.0,skilled,1,1
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1.0,skilled,0,0
2,2096.0,4<=X<7,2.0,male single,49.0,1.0,unskilled resident,0,1
3,7882.0,4<=X<7,2.0,male single,45.0,1.0,skilled,0,1
4,4870.0,1<=X<4,3.0,male single,53.0,2.0,skilled,0,0
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1.0,unskilled resident,0,1
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1.0,high qualif/self emp/mgmt,1,1
997,804.0,>=7,4.0,male single,38.0,1.0,skilled,0,1
998,1845.0,1<=X<4,4.0,male single,23.0,1.0,skilled,1,0
999,4576.0,unemployed,3.0,male single,27.0,1.0,skilled,0,1

In [64]:
df['Existing_credits'] = df['Existing_credits'].astype('int')

In [65]:
df

,Credit_amount,Employment,Installment_commitment,Personal_status,Age,Existing_credits,Job,Own_telephone,Class
0,1169.0,>=7,4.0,male single,67.0,2,skilled,1,1
1,5951.0,1<=X<4,2.0,female div/dep/mar,22.0,1,skilled,0,0
2,2096.0,4<=X<7,2.0,male single,49.0,1,unskilled resident,0,1
3,7882.0,4<=X<7,2.0,male single,45.0,1,skilled,0,1
4,4870.0,1<=X<4,3.0,male single,53.0,2,skilled,0,0
...,...,...,...,...,...,...,...,...,...
995,1736.0,4<=X<7,3.0,female div/dep/mar,31.0,1,unskilled resident,0,1
996,3857.0,1<=X<4,4.0,male div/sep,40.0,1,high qualif/self emp/mgmt,1,1
997,804.0,>=7,4.0,male single,38.0,1,skilled,0,1
998,1845.0,1<=X<4,4.0,male single,23.0,1,skilled,1,0
999,4576.0,unemployed,3.0,male single,27.0,1,skilled,0,1

In [67]:
type(df['Existing_credits'][0])

numpy.int64

In [68]:
df.to_csv('cleaned_credit_customer.csv', index=False)